package logparser.dto;

public enum LogEntryType {
    PROCESS_EVENT,
    RESOURCE_AVAILABLE,
    RESOURCE_UNAVAILABLE,
    PROCESS_FINISHED,
    PROCESS_STARTED,
    PROCESS_SNAPSHOT,
    PROCESS_STATUS_MESSAGE,
    PROCESS_EXIT_CODE,
    SIMULATION_FINISHED,
    UNKNOWN
}
